/* tslint:disable */
/* eslint-disable */
/**
 * URL List API
 * API for managing URL lists         Schema: <a href=\"http://localhost:3001/api-yaml\" target=\"_blank\">http://localhost:3001/api-yaml</a>       
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUrlDto
 */
export interface CreateUrlDto {
    /**
     * The URL to be added
     * @type {string}
     * @memberof CreateUrlDto
     */
    url: string;
    /**
     * The title of the URL
     * @type {string}
     * @memberof CreateUrlDto
     */
    title: string;
    /**
     * A brief description of the URL
     * @type {string}
     * @memberof CreateUrlDto
     */
    description: string;
    /**
     * The order of the URL in the list
     * @type {number}
     * @memberof CreateUrlDto
     */
    order: number;
    /**
     * The ID of the URL list to which this URL belongs
     * @type {string}
     * @memberof CreateUrlDto
     */
    urlListId: string;
}

/**
 * Check if a given object implements the CreateUrlDto interface.
 */
export function instanceOfCreateUrlDto(value: object): value is CreateUrlDto {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    if (!('urlListId' in value) || value['urlListId'] === undefined) return false;
    return true;
}

export function CreateUrlDtoFromJSON(json: any): CreateUrlDto {
    return CreateUrlDtoFromJSONTyped(json, false);
}

export function CreateUrlDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUrlDto {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'title': json['title'],
        'description': json['description'],
        'order': json['order'],
        'urlListId': json['urlListId'],
    };
}

export function CreateUrlDtoToJSON(value?: CreateUrlDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
        'title': value['title'],
        'description': value['description'],
        'order': value['order'],
        'urlListId': value['urlListId'],
    };
}

