/* tslint:disable */
/* eslint-disable */
/**
 * URL List API
 * API for managing URL lists         Schema: <a href=\"http://localhost:3001/api-yaml\" target=\"_blank\">http://localhost:3001/api-yaml</a>       
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUrlListDto
 */
export interface CreateUrlListDto {
    /**
     * The slug of the link unique identifier for the URL list
     * @type {string}
     * @memberof CreateUrlListDto
     */
    slug: string;
    /**
     * The title of the link
     * @type {string}
     * @memberof CreateUrlListDto
     */
    title: string;
}

/**
 * Check if a given object implements the CreateUrlListDto interface.
 */
export function instanceOfCreateUrlListDto(value: object): value is CreateUrlListDto {
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CreateUrlListDtoFromJSON(json: any): CreateUrlListDto {
    return CreateUrlListDtoFromJSONTyped(json, false);
}

export function CreateUrlListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUrlListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'title': json['title'],
    };
}

export function CreateUrlListDtoToJSON(value?: CreateUrlListDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'slug': value['slug'],
        'title': value['title'],
    };
}

