version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: urllist-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: urllist
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
